PRAGMA foreign_keys=OFF;
BEGIN TRANSACTION;

DROP TABLE IF EXISTS region;
CREATE TABLE region(
  num_region TEXT PRIMARY KEY,
  nom_region TEXT,
  capitale TEXT
);
INSERT INTO region VALUES('1','Grand-Est','Strasbourg');
INSERT INTO region VALUES('2','Nouvelle-Aquitaine','Bordeaux');
INSERT INTO region VALUES('3','Auvergne-Rhône-Alpes','Lyon');
INSERT INTO region VALUES('4','Normandie','Rouen');
INSERT INTO region VALUES('5','Bourgogne-Franche-Comté','Dijon');
INSERT INTO region VALUES('6','Bretagne','Rennes');
INSERT INTO region VALUES('7','Centre-Val-de-Loire','Orléans');
INSERT INTO region VALUES('8','Corse','Ajaccio');
INSERT INTO region VALUES('10','Ile-de-France','Paris');
INSERT INTO region VALUES('11','Occitanie','Toulouse');
INSERT INTO region VALUES('12','Hauts-de-France','Lille');
INSERT INTO region VALUES('14','Provence-Alpes-Côte-d''Azur','Marseille');
INSERT INTO region VALUES('13','Pays-de-la-Loire','Nantes');

DROP TABLE IF EXISTS departement;
CREATE TABLE departement(
  num_departement TEXT PRIMARY KEY,
  nom_departement TEXT,
  num_region TEXT
);
INSERT INTO departement VALUES('01','Ain','3');
INSERT INTO departement VALUES('02','Aisne','12');
INSERT INTO departement VALUES('03','Allier','3');
INSERT INTO departement VALUES('04','Alpes de haute provence','14');
INSERT INTO departement VALUES('05','Hautes alpes','14');
INSERT INTO departement VALUES('06','Alpes maritimes','14');
INSERT INTO departement VALUES('07','Ardèche','3');
INSERT INTO departement VALUES('08','Ardennes','1');
INSERT INTO departement VALUES('09','Ariège','11');
INSERT INTO departement VALUES('10','Aube','1');
INSERT INTO departement VALUES('11','Aude','11');
INSERT INTO departement VALUES('12','Aveyron','11');
INSERT INTO departement VALUES('13','Bouches du rhône','14');
INSERT INTO departement VALUES('14','Calvados','4');
INSERT INTO departement VALUES('15','Cantal','3');
INSERT INTO departement VALUES('16','Charente','2');
INSERT INTO departement VALUES('17','Charente maritime','2');
INSERT INTO departement VALUES('18','Cher','7');
INSERT INTO departement VALUES('19','Corrèze','2');
INSERT INTO departement VALUES('20','Corse','8');
INSERT INTO departement VALUES('21','Côte d''or','5');
INSERT INTO departement VALUES('22','Côtes d''Armor','6');
INSERT INTO departement VALUES('23','Creuse','2');
INSERT INTO departement VALUES('24','Dordogne','2');
INSERT INTO departement VALUES('25','Doubs','5');
INSERT INTO departement VALUES('26','Drôme','3');
INSERT INTO departement VALUES('27','Eure','4');
INSERT INTO departement VALUES('28','Eure et Loir','7');
INSERT INTO departement VALUES('29','Finistère','6');
INSERT INTO departement VALUES('30','Gard','11');
INSERT INTO departement VALUES('31','Haute garonne','11');
INSERT INTO departement VALUES('32','Gers','11');
INSERT INTO departement VALUES('33','Gironde','2');
INSERT INTO departement VALUES('34','Hérault','11');
INSERT INTO departement VALUES('35','Ile et Vilaine','6');
INSERT INTO departement VALUES('36','Indre','7');
INSERT INTO departement VALUES('37','Indre et Loire','7');
INSERT INTO departement VALUES('38','Isère','3');
INSERT INTO departement VALUES('39','Jura','5');
INSERT INTO departement VALUES('40','Landes','2');
INSERT INTO departement VALUES('41','Loir et Cher','7');
INSERT INTO departement VALUES('42','Loire','3');
INSERT INTO departement VALUES('43','Haute Loire','3');
INSERT INTO departement VALUES('44','Loire Atlantique','13');
INSERT INTO departement VALUES('45','Loiret','7');
INSERT INTO departement VALUES('46','Lot','11');
INSERT INTO departement VALUES('47','Lot et Garonne','2');
INSERT INTO departement VALUES('48','Lozère','11');
INSERT INTO departement VALUES('49','Maine et Loire','13');
INSERT INTO departement VALUES('50','Manche','4');
INSERT INTO departement VALUES('51','Marne','1');
INSERT INTO departement VALUES('52','Haute Marne','1');
INSERT INTO departement VALUES('53','Mayenne','13');
INSERT INTO departement VALUES('54','Meurthe et Moselle','1');
INSERT INTO departement VALUES('55','Meuse','1');
INSERT INTO departement VALUES('56','Morbihan','6');
INSERT INTO departement VALUES('57','Moselle','1');
INSERT INTO departement VALUES('58','Nièvre','5');
INSERT INTO departement VALUES('59','Nord','12');
INSERT INTO departement VALUES('60','Oise','12');
INSERT INTO departement VALUES('61','Orne','4');
INSERT INTO departement VALUES('62','Pas de Calais','12');
INSERT INTO departement VALUES('63','Puy de Dôme','3');
INSERT INTO departement VALUES('64','Pyrénées Atlantiques','2');
INSERT INTO departement VALUES('65','Hautes Pyrénées','11');
INSERT INTO departement VALUES('66','Pyrénées Orientales','11');
INSERT INTO departement VALUES('67','Bas Rhin','1');
INSERT INTO departement VALUES('68','Haut Rhin','1');
INSERT INTO departement VALUES('69','Rhône','3');
INSERT INTO departement VALUES('70','Haute Saône','5');
INSERT INTO departement VALUES('71','Saône et Loire','5');
INSERT INTO departement VALUES('72','Sarthe','13');
INSERT INTO departement VALUES('73','Savoie','3');
INSERT INTO departement VALUES('74','Haute Savoie','3');
INSERT INTO departement VALUES('75','Paris','10');
INSERT INTO departement VALUES('76','Seine Maritime','4');
INSERT INTO departement VALUES('77','Seine et Marne','10');
INSERT INTO departement VALUES('78','Yvelines','10');
INSERT INTO departement VALUES('79','Deux Sèvres','2');
INSERT INTO departement VALUES('80','Somme','12');
INSERT INTO departement VALUES('81','Tarn','11');
INSERT INTO departement VALUES('82','Tarn et Garonne','11');
INSERT INTO departement VALUES('83','Var','14');
INSERT INTO departement VALUES('84','Vaucluse','14');
INSERT INTO departement VALUES('85','Vendée','13');
INSERT INTO departement VALUES('86','Vienne','2');
INSERT INTO departement VALUES('87','Haute Vienne','2');
INSERT INTO departement VALUES('88','Vosges','1');
INSERT INTO departement VALUES('89','Yonne','5');
INSERT INTO departement VALUES('90','Territoire de Belfort','5');
INSERT INTO departement VALUES('91','Essonne','10');
INSERT INTO departement VALUES('92','Hauts de Seine','10');
INSERT INTO departement VALUES('93','Seine Saint Denis','10');
INSERT INTO departement VALUES('94','Val de Marne','10');
INSERT INTO departement VALUES('95','Val d''Oise','10');
COMMIT;
